
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyaddcvpllgppxeyyqqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YWRkY3ZwbGxncHB4ZXl5cXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTM4ODksImV4cCI6MjA2Mjk4OTg4OX0.QSMxd81BNWfW-Wd-x9zHt-Cs6B8o0bWn0qb6E-k5GXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
