// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database as DatabaseType } from './types';

const SUPABASE_URL = "https://oyaddcvpllgppxeyyqqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YWRkY3ZwbGxncHB4ZXl5cXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTM4ODksImV4cCI6MjA2Mjk4OTg4OX0.QSMxd81BNWfW-Wd-x9zHt-Cs6B8o0bWn0qb6E-k5GXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<DatabaseType>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Update the Database type for portfolio to include descricao
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          nome: string | null;
          email: string | null;
          telefone: string | null;
          senha_hash: string | null;
          tipo_inicial: string;
          tem_perfil_profissional: boolean;
          data_cadastro: string;
        };
        Insert: {
          id?: string;
          nome?: string | null;
          email?: string | null;
          telefone?: string | null;
          senha_hash?: string | null;
          tipo_inicial?: string;
          tem_perfil_profissional?: boolean;
          data_cadastro?: string;
        };
        Update: {
          id?: string;
          nome?: string | null;
          email?: string | null;
          telefone?: string | null;
          senha_hash?: string | null;
          tipo_inicial?: string;
          tem_perfil_profissional?: boolean;
          data_cadastro?: string;
        };
      };
      user_settings: {
        Row: {
          id: string;
          user_id: string;
          settings: Record<string, boolean>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          settings?: Record<string, boolean>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          settings?: Record<string, boolean>;
          created_at?: string;
          updated_at?: string;
        };
      };
      profissionais: {
        Row: {
          id: string;
          user_id: string;
          nome_artistico: string | null;
          tipo_profissional: string | null;
          instrumentos: string[] | null;
          subgeneros: string[] | null;
          bio: string | null;
          cidade: string | null;
          estado: string | null;
          cache_hora: number | null;
          cache_evento: number | null;
          status: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          nome_artistico?: string | null;
          tipo_profissional?: string | null;
          instrumentos?: string[] | null;
          subgeneros?: string[] | null;
          bio?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cache_hora?: number | null;
          cache_evento?: number | null;
          status?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          nome_artistico?: string | null;
          tipo_profissional?: string | null;
          instrumentos?: string[] | null;
          subgeneros?: string[] | null;
          bio?: string | null;
          cidade?: string | null;
          estado?: string | null;
          cache_hora?: number | null;
          cache_evento?: number | null;
          status?: string;
        };
      };
      eventos: {
        Row: {
          id: string;
          titulo: string | null;
          descricao: string | null;
          data: string | null;
          local: string | null;
          servicos_requeridos: string[] | null;
          contratante_id: string;
          status: string;
        };
        Insert: {
          id?: string;
          titulo?: string | null;
          descricao?: string | null;
          data?: string | null;
          local?: string | null;
          servicos_requeridos?: string[] | null;
          contratante_id: string;
          status?: string;
        };
        Update: {
          id?: string;
          titulo?: string | null;
          descricao?: string | null;
          data?: string | null;
          local?: string | null;
          servicos_requeridos?: string[] | null;
          contratante_id?: string;
          status?: string;
        };
      };
      candidaturas: {
        Row: {
          id: string;
          evento_id: string;
          profissional_id: string;
          mensagem: string | null;
          status: string;
          data_candidatura: string;
        };
        Insert: {
          id?: string;
          evento_id: string;
          profissional_id: string;
          mensagem?: string | null;
          status?: string;
          data_candidatura?: string;
        };
        Update: {
          id?: string;
          evento_id?: string;
          profissional_id?: string;
          mensagem?: string | null;
          status?: string;
          data_candidatura?: string;
        };
      };
      portfolio: {
        Row: {
          id: string;
          profissional_id: string | null;
          tipo: string | null;
          url: string | null;
          descricao: string | null;
        };
        Insert: {
          id?: string;
          profissional_id?: string | null;
          tipo?: string | null;
          url?: string | null;
          descricao?: string | null;
        };
        Update: {
          id?: string;
          profissional_id?: string | null;
          tipo?: string | null;
          url?: string | null;
          descricao?: string | null;
        };
      };
      avaliacoes: {
        Row: {
          id: string;
          profissional_id: string;
          evento_id: string;
          contratante_id: string;
          nota: number | null;
          comentario: string | null;
          data_avaliacao: string;
        };
        Insert: {
          id?: string;
          profissional_id: string;
          evento_id: string;
          contratante_id: string;
          nota?: number | null;
          comentario?: string | null;
          data_avaliacao?: string;
        };
        Update: {
          id?: string;
          profissional_id?: string;
          evento_id?: string;
          contratante_id?: string;
          nota?: number | null;
          comentario?: string | null;
          data_avaliacao?: string;
        };
      };
      carrinhos: {
        Row: {
          id: string;
          contratante_id: string;
          status: string;
          data_atualizacao: string;
        };
        Insert: {
          id?: string;
          contratante_id: string;
          status?: string;
          data_atualizacao?: string;
        };
        Update: {
          id?: string;
          contratante_id?: string;
          status?: string;
          data_atualizacao?: string;
        };
      };
      carrinho_itens: {
        Row: {
          id: string;
          carrinho_id: string;
          profissional_id: string;
          servico: string | null;
          preco: number | null;
        };
        Insert: {
          id?: string;
          carrinho_id: string;
          profissional_id: string;
          servico?: string | null;
          preco?: number | null;
        };
        Update: {
          id?: string;
          carrinho_id?: string;
          profissional_id?: string;
          servico?: string | null;
          preco?: number | null;
        };
      };
      reservas: {
        Row: {
          id: string;
          profissional_id: string;
          contratante_id: string;
          evento_id: string;
          status: string;
          data_reserva: string;
        };
        Insert: {
          id?: string;
          profissional_id: string;
          contratante_id: string;
          evento_id: string;
          status?: string;
          data_reserva?: string;
        };
        Update: {
          id?: string;
          profissional_id?: string;
          contratante_id?: string;
          evento_id?: string;
          status?: string;
          data_reserva?: string;
        };
      };
      pagamentos: {
        Row: {
          id: string;
          reserva_id: string;
          valor_total: number | null;
          metodo: string | null;
          status: string | null;
          comprovante_url: string | null;
          data_pagamento: string;
        };
        Insert: {
          id?: string;
          reserva_id: string;
          valor_total?: number | null;
          metodo?: string | null;
          status?: string | null;
          comprovante_url?: string | null;
          data_pagamento?: string;
        };
        Update: {
          id?: string;
          reserva_id?: string;
          valor_total?: number | null;
          metodo?: string | null;
          status?: string | null;
          comprovante_url?: string | null;
          data_pagamento?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};

// Create a Supabase client
export const supabase = createClient<Database>(
  'https://oyaddcvpllgppxeyyqqu.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YWRkY3ZwbGxncHB4ZXl5cXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTM4ODksImV4cCI6MjA2Mjk4OTg4OX0.QSMxd81BNWfW-Wd-x9zHt-Cs6B8o0bWn0qb6E-k5GXM'
);

export default supabase;
