
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Define our database schema
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          biography: string | null;
          city: string | null;
          state: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          full_name?: string;
          biography?: string | null;
          city?: string | null;
          state?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          biography?: string | null;
          city?: string | null;
          state?: string | null;
          created_at?: string;
        };
      };
      professionals: {
        Row: {
          id: string;
          artistic_name: string | null;
          type: string;
          services: string[] | null;
          genres: string[] | null;
          rating: number | null;
          hourly_rate: number | null;
          event_rate: number | null;
          created_at: string;
        };
        Insert: {
          id: string;
          artistic_name?: string | null;
          type: string;
          services?: string[] | null;
          genres?: string[] | null;
          rating?: number | null;
          hourly_rate?: number | null;
          event_rate?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          artistic_name?: string | null;
          type?: string;
          services?: string[] | null;
          genres?: string[] | null;
          rating?: number | null;
          hourly_rate?: number | null;
          event_rate?: number | null;
          created_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          creator_id: string;
          name: string;
          description: string;
          date: string;
          time: string;
          location: string;
          city: string;
          state: string;
          is_public: boolean;
          required_services: string[];
          created_at: string;
        };
        Insert: {
          id?: string;
          creator_id: string;
          name: string;
          description: string;
          date: string;
          time: string;
          location: string;
          city: string;
          state: string;
          is_public: boolean;
          required_services: string[];
          created_at?: string;
        };
        Update: {
          id?: string;
          creator_id?: string;
          name?: string;
          description?: string;
          date?: string;
          time?: string;
          location?: string;
          city?: string;
          state?: string;
          is_public?: boolean;
          required_services?: string[];
          created_at?: string;
        };
      };
      applications: {
        Row: {
          id: string;
          event_id: string;
          professional_id: string;
          status: string;
          message: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          professional_id: string;
          status?: string;
          message: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          professional_id?: string;
          status?: string;
          message?: string;
          created_at?: string;
        };
      };
      bookings: {
        Row: {
          id: string;
          client_id: string;
          professional_id: string;
          event_id: string | null;
          status: string;
          date: string;
          time: string;
          duration: number;
          total_amount: number;
          payment_status: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          professional_id: string;
          event_id?: string | null;
          status?: string;
          date: string;
          time: string;
          duration: number;
          total_amount: number;
          payment_status?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          professional_id?: string;
          event_id?: string | null;
          status?: string;
          date?: string;
          time?: string;
          duration?: number;
          total_amount?: number;
          payment_status?: string;
          created_at?: string;
        };
      };
      reviews: {
        Row: {
          id: string;
          reviewer_id: string;
          reviewed_id: string;
          booking_id: string | null;
          rating: number;
          comment: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          reviewer_id: string;
          reviewed_id: string;
          booking_id?: string | null;
          rating: number;
          comment?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          reviewer_id?: string;
          reviewed_id?: string;
          booking_id?: string | null;
          rating?: number;
          comment?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
  };
};

const SUPABASE_URL = "https://oyaddcvpllgppxeyyqqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YWRkY3ZwbGxncHB4ZXl5cXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTM4ODksImV4cCI6MjA2Mjk4OTg4OX0.QSMxd81BNWfW-Wd-x9zHt-Cs6B8o0bWn0qb6E-k5GXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
